Hash: clean
	@echo "Compilando o programa HashTable"
	@gcc  HashTable.c -o HashTable
	@chmod +x HashTable
	@./HashTable
	@echo "===================================================================="
EstudandoInserir: clean
	@echo "Compilando o programa EstudandoInserir"
	@gcc  EstudandoInserir.c -o EstudandoInserir
	@chmod +x EstudandoInserir
	@./EstudandoInserir
	@echo "===================================================================="
ListaEncadeada1: clean
	@echo "Compilando o programa ListaEncadeada1"
	@gcc  ListaEncadeada1.c -o ListaEncadeada1
	@chmod +x ListaEncadeada1
	@./ListaEncadeada1
	@echo "===================================================================="
ImprimirEndereco: clean
	@echo "Compilando o programa ImprimirEndereco"
	@gcc  ImprimirEndereco.c -o ImprimirEndereco
	@chmod +x ImprimirEndereco
	@./ImprimirEndereco
	@echo "===================================================================="
trocaAeB: clean
	@echo "Compilando o programa trocaAeB"
	@gcc  trocaAeB.c -o trocaAeB
	@chmod +x trocaAeB
	@./trocaAeB
	@echo "===================================================================="
MenorEmaior: clean
	@echo "Compilando o programa MenorEmaior"
	@gcc  MenorEmaior.c -o MenorEmaior
	@chmod +x MenorEmaior
	@./MenorEmaior
	@echo "===================================================================="
Pointer191: clean
	@echo "Compilando o programa Pointer191"
	@gcc  Pointer191.c -o Pointer191
	@chmod +x Pointer191
	@./Pointer191
	@echo "===================================================================="
Pointer190: clean
	@echo "Compilando o programa Pointer190"
	@gcc  Pointer190.c -o Pointer190
	@chmod +x Pointer190
	@./Pointer190
	@echo "===================================================================="
Pointer188: clean
	@echo "Compilando o programa Pointer188"
	@gcc  Pointer188.c -o Pointer188
	@chmod +x Pointer188
	@./Pointer188
	@echo "===================================================================="
Pointer187: clean
	@echo "Compilando o programa Pointer187"
	@gcc  Pointer187.c -o Pointer187
	@chmod +x Pointer187
	@./Pointer187
	@echo "===================================================================="Pointer187: clean
	@echo "Compilando o programa Pointer187"
	@gcc  Pointer187.c -o Pointer187
	@chmod +x Pointer187
	@./Pointer187
	@echo "===================================================================="
Pointer1: clean
	@echo "Compilando o programa Pointer"
	@gcc  Pointer1.c -o Pointer1
	@chmod +x Pointer1
	@./Pointer1
	@echo "===================================================================="
Pointer: clean
	@echo "Compilando o programa Pointer"
	@gcc  Pointer.c -o Pointer
	@chmod +x Pointer
	@./Pointer
	@echo "===================================================================="
Market: clean
	@echo "Compilando o código Market"
	@gcc Market.c -o Market
	@chmod +x Market
	@./Market
	@echo "Executando o código"
StructEmStruct: clean
	@echo "Compilando o programa StructEmStruct"
	@gcc  StructEmStruct.c -o StructEmStruct
	@chmod +x StructEmStruct
	@./StructEmStruct
	@echo "===================================================================="
Struct: clean
	@echo "Compilando o programa Struct"
	@gcc  Struct.c -o Struct
	@chmod +x Struct
	@./Struct
	@echo "===================================================================="
StringTreino: clean
	@echo "Compilando o programa StringTreino"
	@gcc  StringTreino.c -o StringTreino
	@chmod +x StringTreino
	@./StringTreino
	@echo "===================================================================="
Alocacao202: clean
	@echo "Compilando o programa Alocacao202"
	@gcc  Alocacao202.c -o Alocacao202
	@chmod +x Alocacao202
	@./Alocacao202
	@echo "===================================================================="
Alocacao201: clean
	@echo "Compilando o programa Alocacao201"
	@gcc  Alocacao201.c -o Alocacao201
	@chmod +x Alocacao201
	@./Alocacao201
	@echo "===================================================================="
Alocacao200: clean
	@echo "Compilando o programa Alocacao200"
	@gcc  Alocacao200.c -o Alocacao200
	@chmod +x Alocacao200
	@./Alocacao200
	@echo "===================================================================="
Alocacao199: clean
	@echo "Compilando o programa Alocacao199"
	@gcc  Alocacao199.c -o Alocacao199
	@chmod +x Alocacao199
	@./Alocacao199
	@echo "===================================================================="
Alocacao198: clean
	@echo "Compilando o programa Alocacao198"
	@gcc  Alocacao198.c -o Alocacao198
	@chmod +x Alocacao198
	@./Alocacao198
	@echo "===================================================================="
AlocacaoDeMemoria: clean
	@echo "Compilando o programa AlocacaoDeMemoria"
	@gcc  Alocacao197.c -o AlocacaoDeMemoria
	@chmod +x AlocacaoDeMemoria
	@./AlocacaoDeMemoria
	@echo "===================================================================="
ListaGeneralizada: clean
	@echo "Compilando o programa Lista Generalizada"
	@gcc  --std=c99 -DLOG_USE_COLOR log.h log.c ListaGeneralizada.c ListaGeneralizada.h ListaGeneralizadaTeste.c -o ListaGeneralizada
	
	@chmod +x ListaGeneralizada
	
	@./ListaGeneralizada
	@echo "===================================================================="
Linkedlist: clean
	@echo "Compilando o programa Linkedlist"
	@gcc  --std=c99 -DLOG_USE_COLOR log.h log.c Linkedlist.c Linkedlist.h LinkedlistTest.c -o Linkedlist
	
	@chmod +x Linkedlist
	
	@./Linkedlist
	@echo "===================================================================="
Ponteiro: clean
	@echo "Compilando o programa Ponteiro"
	@gcc testepointer.c -o Ponteiro
	@echo "Tornando o programa Ponteiro executável"
	@chmod +x Ponteiro
	@echo "Executando o progrma Ponteiro"
	@./Ponteiro
	@echo "===================================================================="
ola: clean
	@echo "===================================================================="
	@echo "						PROGRAMA OLA								   "
	@echo "===================================================================="
	@echo "Compilando o programa olamundo"
	@gcc olamundo.c -o ola
	@echo "Tornando o programa olamundo executável"
	@chmod +x ola
	@echo "Executando o progrma olamundo"
	./ola
	@echo "===================================================================="
clean:
	@echo "===================================================================="
	@echo " Removendo os programas compilados							   "
	@echo "===================================================================="
	@rm -f ola
	@echo "===================================================================="
help:
	@echo "===================================================================="
	@echo "								AJUDA								   "
	@echo "===================================================================="
	@echo "help			| ajuda"
	@echo "ola			| executa mensagem de teste"
	@echo "clean		| apaga códigos compilados"